// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Avatar.tsx";
import * as $1 from "./routes/Tweet.tsx";
import * as $2 from "./routes/api/git/commits/latest.ts";
import * as $3 from "./routes/api/git/webhook.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/math/add.ts";
import * as $6 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/Avatar.tsx": $0,
    "./routes/Tweet.tsx": $1,
    "./routes/api/git/commits/latest.ts": $2,
    "./routes/api/git/webhook.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/math/add.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
