// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/git/commits/latest.ts";
import * as $2 from "./routes/api/git/webhook.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/math/add.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/base_node.tsx";
import * as $$2 from "./islands/connection.tsx";
import * as $$3 from "./islands/workspace.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/git/commits/latest.ts": $1,
    "./routes/api/git/webhook.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/math/add.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/base_node.tsx": $$1,
    "./islands/connection.tsx": $$2,
    "./islands/workspace.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
